[package]
name = "chama_savings"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "=20.3.0"

[dev-dependencies]
soroban-sdk = { version = "=20.3.0", features = ["testutils"] }
